server:
  port: 8004

spring:
  application:
    name: amount-rate-service

  datasource:
    url: jdbc:postgresql://localhost:5432/amount_rate_db
    username: amount_rate_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true