server:
  port: 8007

spring:
  application:
    name: user-role-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_role_db
    username: user_role_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true